"""New models integrated fix

Revision ID: 098b316048df
Revises: c0797ca226ce
Create Date: 2025-03-08 23:47:52.244308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '098b316048df'
down_revision = 'c0797ca226ce'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE TYPE userrole AS ENUM ('doctor', 'patient', 'admin');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_date', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicalrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('record_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('pdf_resume', sa.LargeBinary(), nullable=True),
    sa.Column('scanner_image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role', sa.Enum('doctor', 'patient', 'admin', name='userrole'), nullable=True))
    op.add_column('user', sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('user', sa.Column('doctor_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'doctor_id')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'specialization')
    op.drop_column('user', 'role')
    op.drop_table('medicalrecord')
    op.drop_table('appointment')
    # ### end Alembic commands ###
