"""router fix

Revision ID: 186d4f53769d
Revises: 2fcad652f4bf
Create Date: 2025-03-09 08:04:24.797824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '186d4f53769d'
down_revision = '2fcad652f4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
