"""remove roles

Revision ID: 3b5b658b5e3d
Revises: 76b31b94a174
Create Date: 2025-03-09 01:24:06.909520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b5b658b5e3d'
down_revision = '76b31b94a174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('doctor', 'patient', 'admin', name='userrole'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
