"""last and last

Revision ID: 8622fe9a5f1f
Revises: f497746a4f93
Create Date: 2025-03-09 00:55:04.064840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8622fe9a5f1f'
down_revision = 'f497746a4f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('doctor', 'patient', 'admin', name='userrole'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1),
               type_=postgresql.ENUM('doctor', 'patient', 'admin', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
