"""last and least

Revision ID: 90338d211861
Revises: 6099477c327b
Create Date: 2025-03-09 00:47:36.723732

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90338d211861'
down_revision = '6099477c327b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('doctor', 'patient', 'admin', name='userrole'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=postgresql.ENUM('doctor', 'patient', 'admin', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
