"""last and least fix

Revision ID: f497746a4f93
Revises: 90338d211861
Create Date: 2025-03-09 00:52:06.644047

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f497746a4f93'
down_revision = '90338d211861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('doctor', 'patient', 'admin', name='userrole'),
               type_=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('doctor', 'patient', 'admin', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
