name: Issue Manager

on:
  schedule:
    - cron: "21 17 * * *"
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  issue-manager:
    if: github.repository_owner == 'ahmedmhedhbii'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: tiangolo/issue-manager@0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            {
              "answered": {
                "delay": 864000,
                "message": "Assuming the original need was handled, this issue will now be closed. Feel free to add more details if needed."
              },
              "waiting": {
                "delay": 2628000,
                "message": "This issue has been inactive for a while and will be closed. Please reopen if you still need help."
              },
              "invalid": {
                "delay": 0,
                "message": "This issue was marked invalid and will be closed."
              }
            }
